version: '3.8'

services:
  todo-app:
    build: .
    container_name: todo-app
    ports:
      - "3000:3000"
    volumes:
      - todo_data:/app/data
    environment:
      - NODE_ENV="production"
    restart: unless-stopped
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: mohamed
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: todo_db

volumes:
  todo_data:
  postgres_data: